### ISSUE TITLE
Pull data from Android apps

### ISSUE THREAD

**Issue by gregbartell** [TheoBr/inSquare#6]
Another open-ended problem. Ideally, the time should hide itself (either fade out, or move to the top corner of the screen) and incoming messages and similar would take its place on screen. Not sure how to do it, but someone has done it - see link.
http://forums.getpebble.com/discussion/21015/pebble-emulator-to-android-app-message-bridge

**Comment by t3dotgg** [comment]
All notifications are automatically handled by Pebble. By making a watch face, we are simply making the screen that is displayed when there are no messages or notifications of any form. Pretty simple stuff

**Comment by gregbartell** [comment]
Then what was that link you sent to me about?

**Comment by t3dotgg** [comment]
How to connect your phone to the emulator, so you can change settings in the watch face and such
